djProject/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('web/', include('web.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_bill/', views.get_bill, name='get_bill'),
    path('<int:user_id>/', views.save_user, name='save_user'),
    path('update_trent/', views.update_trent, name='update_trent'),
    path('delete_trent/', views.delete_trent, name='delete_trent'),
    path('check_from/', views.check_user_form, name='check_user_form'),
    path('check_user/', views.check_user, name='check_user'),
    path('add_form/', views.add_user_form, name='add_user_form'),
    path('add_user/', views.add_user, name='add_user'),
    path('add_user_image/', views.add_user_image, name='add_user_image'),
    path('upload_handle/', views.upload_handle, name='upload_handle'),
    path('show_avatar/', views.show_avatar, name='show_avatar'),
]

web/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    """
    创建用户表
    """
    name = models.CharField(max_length=128, null=True, unique=True, verbose_name='昵称')
    phone = models.CharField(max_length=128, null=True, unique=True, verbose_name='手机号')
    password = models.CharField(max_length=128, null=True, unique=True, verbose_name='密码')
    avatar = models.ImageField(upload_to='users', max_length=100, blank=True, null=True, verbose_name='用户头像')

    # meta类是配合admin进行管理的
    class Meta:
        db_table = 'web_user'
        ordering = ['name']  # 默认正序，倒序的话是'-name'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

web/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from utils.uploads import getNewName
from .models import User
from django.conf import settings
import os

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def get_bill(request):
    # 获取所有用户
    # all_users = User.objects.all()

    # 获取有条件的获取用户
    user = User.objects.filter(name='bill')

    return HttpResponse(user[0].phone)


def save_user(request, user_id):
    user = User()
    user.id = user_id
    user.name = 'trent'
    user.phone = '13888888888'
    user.password = '2345'

    # 调用save则保存数据到数据库中
    user.save()
    return HttpResponse('储存这个user成功')


def update_trent(request):
    User.objects.filter(name='trent').update(phone='12388888888', password='3456')
    return HttpResponse('更新trent的信息成功')


def delete_trent(request):
    User.objects.filter(name='trent').delete()

    return HttpResponse('删除trent成功')

def check_user_form(request):
    return render(request, 'users/check_user_form.html')

def check_user(request):
    request.encoding = 'utf-8'
    if 'username' in request.GET:
        user = get_object_or_404(User, name = request.GET['username'])
        user_info = {'user_id':user.id, 'user_name':user.name, 'user_phone':user.phone, 'user_password':user.password}
    return render(request, 'users/show_user.html', {'user_info':user_info})

def add_user_form(request):
    return render(request, 'users/add_user_form.html')

def add_user(request):
    if request.method=='GET':
        return render(request,'users/add_user_form.html')
    else:
        username=request.POST.get('username','')
        phone = request.POST.get('phone', '')
        password=request.POST.get('password','')

        user = User()
        user.name = username
        user.phone = phone
        user.password = password
        user.save()

        return HttpResponse('username='+username+"&userphone="+phone+"&password="+password+" 保存成功")

def add_user_image(request):
    return render(request, 'users/add_user_image.html')

def upload_handle(request):
    # 获取一个文件管理器对象
    file = request.FILES['pic']

    # 保存文件
    new_name = getNewName('avatar')

    where = '%s/users/%s' % (settings.MEDIA_ROOT, new_name)
    content = file.chunks()
    with open(where, 'wb') as f:
        for i in content:
            f.write(i)

    # 保存文件上传的记录
    User.objects.filter(name='trent').update(avatar=new_name)
    # 返回的httpresponse
    return HttpResponse('ok')

def show_avatar(request):
    user = User.objects.filter(name='trent')[0]
    avatarName = str(user.avatar)
    # avatarUrl = '%s/users/%s' % (settings.MEDIA_URL, avatarName) # 另一种写法
    avatarUrl = os.path.join(settings.MEDIA_URL, 'users', avatarName)
    avatar_info = {'userName':'trent', 'avatarUrl': avatarUrl}
    return render(request, 'users/show_avatar.html', {'avatar_info':avatar_info})

templates/users/add_user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>POST Params</title>
</head>
<body>
<form action="{% url 'users:add_user' %}" method="post" >
    {%csrf_token%} {# csrf_token用来验证 #}
    UserName:<input type="text" name="username"/>
    Phone:<input type="text" name="phone"/>
    Password:<input type="password" name="password"/>
    <input type="submit" value="Submit">
</form>
</body>
</html>

templates/users/add_user_image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        img{
            border-radius: 50%;
            width: 100px;
            height: 100px;
        }
    </style>
</head>
<body>
    <form action="{% url 'users:upload_handle'%}" enctype='multipart/form-data' method="post">
        {% csrf_token %}
        <p>选择图片：<input type="file" name="pic"></p>
        <p><input type="submit" value="上传头像"></p>
    </form>
</body>
</html>

templates/users/check_user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'users:check_user' %}" method="get" >
        UserName:<input type="text" name="username"/>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/users/show_avatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>{{ avatar_info.userName }}</p>
<img src="{{  avatar_info.avatarUrl }}"/>
</body>
</html>

templates/users/show_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        <li>{{ user_info.user_id }}</li>
        <li>{{ user_info.user_name }}</li>
        <li>{{ user_info.user_phone }}</li>
        <li>{{ user_info.user_password }}</li>
    </ul>
</body>
</html>